#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : systemd-bootchart
Version  : 233
Release  : 33
URL      : https://github.com/systemd/systemd-bootchart/releases/download/v233/systemd-bootchart-233.tar.xz
Source0  : https://github.com/systemd/systemd-bootchart/releases/download/v233/systemd-bootchart-233.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: systemd-bootchart-license = %{version}-%{release}
Requires: systemd-bootchart-man = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(libsystemd)
Patch1: 0001-Hardcode-clear-defaults.patch
Patch2: 0002-bootchart-drop-log_info-spam-to-serial-console.patch
Patch3: 0003-Do-not-use-urandom-during-boot.patch
Patch4: 0005-Mount-proc-early-during-boot.patch
Patch5: 0006-Delay-writing-out-the-chart-result.patch
Patch6: 0008-Prevent-null-deref-detecting-idle.patch

%description
For systemd-bootchart, several proc debug interfaces are required in the kernel config:
CONFIG_SCHEDSTATS
below is optional, for additional info:
CONFIG_SCHED_DEBUG

%package extras
Summary: extras components for the systemd-bootchart package.
Group: Default

%description extras
extras components for the systemd-bootchart package.


%package license
Summary: license components for the systemd-bootchart package.
Group: Default

%description license
license components for the systemd-bootchart package.


%package man
Summary: man components for the systemd-bootchart package.
Group: Default

%description man
man components for the systemd-bootchart package.


%prep
%setup -q -n systemd-bootchart-233
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570734504
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export SOURCE_DATE_EPOCH=1570734504
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/systemd-bootchart
cp LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/systemd-bootchart/LICENSE.GPL2
cp LICENSE.LGPL2.1 %{buildroot}/usr/share/package-licenses/systemd-bootchart/LICENSE.LGPL2.1
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/systemd/systemd-bootchart

%files extras
%defattr(-,root,root,-)
/usr/lib/systemd/system/systemd-bootchart.service

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/systemd-bootchart/LICENSE.GPL2
/usr/share/package-licenses/systemd-bootchart/LICENSE.LGPL2.1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/systemd-bootchart.1
/usr/share/man/man5/bootchart.conf.5
/usr/share/man/man5/bootchart.conf.d.5
